name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: compile
      id: compile
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: compile
        setup-command: ''
        command: g++  --std=c++17 homework.cpp -o homework
        timeout: 10
        max-score: 10
    - name: verify
      id: verify
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: verify
        setup-command: ''
        command: "./homework"
        input: ''
        expected-output: 4 4
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILE_RESULTS: "${{steps.compile.outputs.result}}"
        VERIFY_RESULTS: "${{steps.verify.outputs.result}}"
      with:
        runners: compile,verify
